### ISSUE TITLE
Borr-Geth does not meet criteria (the maw)

### ISSUE THREAD

**Issue by i5o** [cr4ckp0t/AnnounceRare#37]
https://wowhead.com/npc=157833

![image](https://user-images.githubusercontent.com/2650479/124330540-fdb9f580-db63-11eb-880e-5bba3f65b287.png)

could be related to my language being esMX

**Comment by Zuescho** [comment]
Not sure how up to date it is, but some things like the Fallen Charger (https://www.wowhead.com/npc=179460/fallen-charger) worked only once for me to announce.
When they die it works for 100%, i enabled debugging now to see if I can find the reason.
![grafik](https://user-images.githubusercontent.com/13680959/124351719-50df8700-dbfc-11eb-8ada-0a3e9384f946.png)

**Comment by cr4ckp0t** [comment]
The death announcements are bugged, and throttling seems to be wonky. I am still looking into them both.

**Comment by cr4ckp0t** [comment]
It does not use language to determine if a rare can be announced, but rather the NPC's internal ID. It will not announce if the target is dead, but it should notify you that the target you wish to announce is dead, rather than the doesn't meet criterial message. This means it's either not the correct ID, which I just checked and confirmed it is, or it was not detecting being in the correct zone for some reason.

Try to kill him again and try `/rare id` while targeting him, and `/rare zone` while near him. You will have to turn debugging on via `/rare debug` for those commands to work. I will try the same on my end to see if I am able to duplicate the issue.

**Comment by Zuescho** [comment]
Going to look up some mobs.


![grafik](https://user-images.githubusercontent.com/13680959/124388045-36cba480-dce1-11eb-8c05-15f1c140c047.png)

![grafik](https://user-images.githubusercontent.com/13680959/124388821-d9395700-dce4-11eb-95f5-8738cdee4766.png)

![grafik](https://user-images.githubusercontent.com/13680959/124389148-2f5aca00-dce6-11eb-8b31-a61abf742fb4.png)

(First Fallen Charger, works)
![grafik](https://user-images.githubusercontent.com/13680959/124394086-0d6d4180-dcfe-11eb-8aa6-2eb3b6e0c6ed.png)

(Second Fallen Charger, does not work also not after /reload )
![grafik](https://user-images.githubusercontent.com/13680959/124395449-7e175c80-dd04-11eb-82ca-fd6714c7293d.png)

Okay, what i could find out so far (waiting for more Fallen Chargers) could it be that AR will only announce Rares once?
Because i just now found a second Morguliax (ID: 162849) which I could not announce but the first one (last screenshot) worked.

What is happening with Borr-Geth i have no idea (first screenshot, i had him targeted)

Edit 1:
![grafik](https://user-images.githubusercontent.com/13680959/124395934-3940f500-dd07-11eb-8fd3-9c9da57dff5c.png)

I'm confused, now it worked again did not restart wow or anything, just went into another zone for a different rare and came back.

Edit 2: Same zone did not work now
![grafik](https://user-images.githubusercontent.com/13680959/124396176-51654400-dd08-11eb-93bd-932da7481e3c.png)

Edit 3: Went out of the zone cam back still did not work... really not sure what it could be
![grafik](https://user-images.githubusercontent.com/13680959/124396338-3b0bb800-dd09-11eb-929b-b83ffd6d0037.png)

Edit 4: Will stop posting them now until i find out something new.
![grafik](https://user-images.githubusercontent.com/13680959/124396460-fc2a3200-dd09-11eb-96ac-467b394f85fc.png)

**Comment by i5o** [comment]
![image](https://user-images.githubusercontent.com/2650479/124403165-58da1c80-dd0b-11eb-8cb6-515a268f885a.png)
https://es.wowhead.com/npc=179755/erradicaci%C3%B3n

**Comment by cr4ckp0t** [comment]
There is a throttle to prevent spamming, so it should not allow you to announce something soon after making an announcement. I may disable that to see how it handles it, since chats have built in spam protection.

**Comment by cr4ckp0t** [comment]
Okay I think I managed to squash all those bugs in release 3.2.2 that I just pushed to GitHub/Curse. Let me know how it does for you.
